.TH PRESUFF "1" "July 2024" "Jacob Niemeir" "User Commands"
.SH NAME
presuff \- Prepend or append a pattern to the basename of each file in a directory
.SH SYNOPSIS
.B presuff \fR<-b|-e> [-d \fI\,DIRECTORY\/\fR] -p \fI\,PATTERN\/\fR [-x \fI\,EXTENSION\/\fR]

.SH DESCRIPTION
.TP
\fB\-b\fR 
prepend pattern to basenames
.TP
\fB\-d[DIRECTORY]\fR 
specify directory to perform renames in
.TP
\fB\-e\fR 
append pattern to basenames
.TP
\fB\-h\fR 
display program usage
.TP
\fB\-p[PATTERN]\fR 
specify pattern to prepend/append
.TP
\fB\-x[EXTENSION]\fR 
specify extension of files to perform renaming on




.SH COPYRIGHT
Copyright \(co 2024 Jacob Niemeir.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
